// color565.h
// MIT License
// https://opensource.org/licenses/MIT
// Copyright (c) 2026, Lars Schumann, larsi.org@gmail.com
//
// This file was generated by a script. Do not modify by hand. The latest
// version can be downloaded from:
// https://larsi.org/graphics/colors/color565.h
#ifndef COLOR565_H
#define COLOR565_H

#include <stdint.h>

// This panel is RGB565: 5 bits red, 6 green, 5 blue. Masking green to 5
// bits too (rather than keeping its 6th bit) means r == g == b always
// reconstructs to an exact flat gray, and a channel value here is
// exactly what ends up on screen instead of a hair off after silent
// truncation.
//
// +----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
// | 15 | 14 | 13 | 12 | 11 | 10 |  9 |  8 |  7 |  6 |  5 |  4 |  3 |  2 |  1 |  0 |
// | r5 | r4 | r3 | r2 | r1 | g5 | g4 | g3 | g2 | g1 |  0 | b5 | b4 | b3 | b2 | b1 |
// +----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+
constexpr uint16_t rgb565(uint8_t r, uint8_t g, uint8_t b) {
  return ((r & 0xF8) << 8) | ((g & 0xF8) << 3) | (b >> 3);
}

constexpr uint16_t COLOR565_AQUAMARINE          = rgb565(104, 248, 208);
constexpr uint16_t COLOR565_BLACK               = rgb565(  0,   0,   0);
constexpr uint16_t COLOR565_BLUE                = rgb565(  0,   0, 248);
constexpr uint16_t COLOR565_BROWN               = rgb565(152,  48,  48);
constexpr uint16_t COLOR565_BROWN3              = rgb565(208,  48,  48);
constexpr uint16_t COLOR565_BURLYWOOD1          = rgb565(248, 208, 152);
constexpr uint16_t COLOR565_CADET_BLUE          = rgb565(104, 152, 152);
constexpr uint16_t COLOR565_CHARTREUSE3         = rgb565(104, 208,   0);
constexpr uint16_t COLOR565_CHARTREUSE4         = rgb565( 48, 152,   0);
constexpr uint16_t COLOR565_CHOCOLATE           = rgb565(208, 104,  48);
constexpr uint16_t COLOR565_CORAL               = rgb565(248, 104, 104);
constexpr uint16_t COLOR565_CORNFLOWER_BLUE     = rgb565(104, 152, 248);
constexpr uint16_t COLOR565_CRIMSON             = rgb565(208,   0,  48);
constexpr uint16_t COLOR565_CYAN                = rgb565(  0, 248, 248);
constexpr uint16_t COLOR565_DARK_BLUE           = rgb565(  0,   0, 152);
constexpr uint16_t COLOR565_DARK_CHARCOAL       = rgb565( 48,  48,  48);
constexpr uint16_t COLOR565_DARK_GOLDENROD      = rgb565(208, 152,   0);
constexpr uint16_t COLOR565_DARK_GREEN          = rgb565(  0, 104,   0);
constexpr uint16_t COLOR565_DARK_KHAKI          = rgb565(208, 208, 104);
constexpr uint16_t COLOR565_DARK_OLIVE_GREEN    = rgb565(104, 104,  48);
constexpr uint16_t COLOR565_DARK_OLIVE_GREEN1   = rgb565(208, 248, 104);
constexpr uint16_t COLOR565_DARK_OLIVE_GREEN3   = rgb565(152, 208, 104);
constexpr uint16_t COLOR565_DARK_ORANGE2        = rgb565(248, 104,   0);
constexpr uint16_t COLOR565_DARK_ORANGE3        = rgb565(208, 104,   0);
constexpr uint16_t COLOR565_DARK_ORCHID         = rgb565(152,  48, 208);
constexpr uint16_t COLOR565_DARK_ORCHID1        = rgb565(208,  48, 248);
constexpr uint16_t COLOR565_DARK_SEA_GREEN      = rgb565(152, 208, 152);
constexpr uint16_t COLOR565_DARK_SEA_GREEN1     = rgb565(208, 248, 208);
constexpr uint16_t COLOR565_DARK_SEA_GREEN4     = rgb565(104, 152, 104);
constexpr uint16_t COLOR565_DARK_SLATE_BLUE     = rgb565( 48,  48, 152);
constexpr uint16_t COLOR565_DARK_SLATE_GRAY     = rgb565( 48, 104, 104);
constexpr uint16_t COLOR565_DARK_SLATE_GRAY3    = rgb565(104, 208, 208);
constexpr uint16_t COLOR565_DARK_TURQUOISE      = rgb565(  0, 208, 208);
constexpr uint16_t COLOR565_DARK_VIOLET         = rgb565(152,   0, 208);
constexpr uint16_t COLOR565_DEEP_PINK           = rgb565(248,   0, 152);
constexpr uint16_t COLOR565_DEEP_PINK3          = rgb565(208,   0, 104);
constexpr uint16_t COLOR565_DEEP_PINK4          = rgb565(152,   0, 104);
constexpr uint16_t COLOR565_DEEP_SKY_BLUE       = rgb565(  0, 208, 248);
constexpr uint16_t COLOR565_DEEP_SKY_BLUE2      = rgb565(  0, 152, 248);
constexpr uint16_t COLOR565_DEEP_SKY_BLUE3      = rgb565(  0, 152, 208);
constexpr uint16_t COLOR565_DEEP_SKY_BLUE4      = rgb565(  0, 104, 152);
constexpr uint16_t COLOR565_DIM_GRAY            = rgb565(104, 104, 104);
constexpr uint16_t COLOR565_DODGER_BLUE         = rgb565( 48, 152, 248);
constexpr uint16_t COLOR565_DODGER_BLUE3        = rgb565(  0, 104, 208);
constexpr uint16_t COLOR565_FIREBRICK1          = rgb565(248,  48,  48);
constexpr uint16_t COLOR565_FOREST_GREEN        = rgb565( 48, 152,  48);
constexpr uint16_t COLOR565_GOLD                = rgb565(248, 208,   0);
constexpr uint16_t COLOR565_GOLD4               = rgb565(152, 104,   0);
constexpr uint16_t COLOR565_GOLDENROD1          = rgb565(248, 208,  48);
constexpr uint16_t COLOR565_GRAY                = rgb565(152, 152, 152);
constexpr uint16_t COLOR565_GREEN               = rgb565(  0, 152,   0);
constexpr uint16_t COLOR565_GREEN3              = rgb565(  0, 208,   0);
constexpr uint16_t COLOR565_GREEN_YELLOW        = rgb565(152, 248,  48);
constexpr uint16_t COLOR565_HOT_PINK            = rgb565(248, 104, 208);
constexpr uint16_t COLOR565_HOT_PINK2           = rgb565(248, 104, 152);
constexpr uint16_t COLOR565_INDIAN_RED          = rgb565(208, 104, 104);
constexpr uint16_t COLOR565_INDIGO              = rgb565( 48,   0, 152);
constexpr uint16_t COLOR565_KHAKI               = rgb565(248, 248, 152);
constexpr uint16_t COLOR565_LAWN_GREEN          = rgb565(104, 248,   0);
constexpr uint16_t COLOR565_LEMON_CHIFFON       = rgb565(248, 248, 208);
constexpr uint16_t COLOR565_LEMON_CHIFFON3      = rgb565(208, 208, 152);
constexpr uint16_t COLOR565_LIGHT_CORAL         = rgb565(248, 152, 152);
constexpr uint16_t COLOR565_LIGHT_CYAN          = rgb565(208, 248, 248);
constexpr uint16_t COLOR565_LIGHT_GOLDENROD4    = rgb565(152, 152,  48);
constexpr uint16_t COLOR565_LIGHT_GRAY          = rgb565(208, 208, 208);
constexpr uint16_t COLOR565_LIGHT_PINK1         = rgb565(248, 152, 208);
constexpr uint16_t COLOR565_LIGHT_SALMON3       = rgb565(208, 152, 104);
constexpr uint16_t COLOR565_LIGHT_SEA_GREEN     = rgb565( 48, 152, 152);
constexpr uint16_t COLOR565_LIGHT_SKY_BLUE      = rgb565(152, 208, 248);
constexpr uint16_t COLOR565_LIGHT_SLATE_BLUE    = rgb565(152, 104, 248);
constexpr uint16_t COLOR565_LIGHT_STEEL_BLUE    = rgb565(152, 208, 208);
constexpr uint16_t COLOR565_LIGHT_STEEL_BLUE1   = rgb565(208, 208, 248);
constexpr uint16_t COLOR565_LIGHT_YELLOW4       = rgb565(152, 152, 104);
constexpr uint16_t COLOR565_LIME                = rgb565(  0, 248,   0);
constexpr uint16_t COLOR565_LIME_GREEN          = rgb565( 48, 208,  48);
constexpr uint16_t COLOR565_MAGENTA             = rgb565(248,   0, 248);
constexpr uint16_t COLOR565_MAGENTA3            = rgb565(208,   0, 208);
constexpr uint16_t COLOR565_MAROON              = rgb565(152,   0,   0);
constexpr uint16_t COLOR565_MAROON1             = rgb565(248,  48, 208);
constexpr uint16_t COLOR565_MEDIUM_AQUAMARINE   = rgb565(104, 208, 152);
constexpr uint16_t COLOR565_MEDIUM_BLUE         = rgb565(  0,   0, 208);
constexpr uint16_t COLOR565_MEDIUM_ORCHID2      = rgb565(208, 104, 248);
constexpr uint16_t COLOR565_MEDIUM_PURPLE       = rgb565(152, 104, 208);
constexpr uint16_t COLOR565_MEDIUM_PURPLE1      = rgb565(152, 152, 248);
constexpr uint16_t COLOR565_MEDIUM_SEA_GREEN    = rgb565( 48, 208, 104);
constexpr uint16_t COLOR565_MEDIUM_SLATE_BLUE   = rgb565(104, 104, 248);
constexpr uint16_t COLOR565_MEDIUM_SPRING_GREEN = rgb565(  0, 248, 152);
constexpr uint16_t COLOR565_MEDIUM_VIOLET_RED   = rgb565(208,   0, 152);
constexpr uint16_t COLOR565_MIDNIGHT_BLUE       = rgb565(  0,   0, 104);
constexpr uint16_t COLOR565_OLIVE               = rgb565(152, 152,   0);
constexpr uint16_t COLOR565_OLIVE_DRAB          = rgb565(104, 152,  48);
constexpr uint16_t COLOR565_OLIVE_DRAB1         = rgb565(208, 248,  48);
constexpr uint16_t COLOR565_ORANGE              = rgb565(248, 152,   0);
constexpr uint16_t COLOR565_ORANGE_RED          = rgb565(248,  48,   0);
constexpr uint16_t COLOR565_ORANGE_RED3         = rgb565(208,  48,   0);
constexpr uint16_t COLOR565_ORCHID              = rgb565(208, 104, 208);
constexpr uint16_t COLOR565_ORCHID2             = rgb565(248, 104, 248);
constexpr uint16_t COLOR565_ORCHID4             = rgb565(152,  48, 152);
constexpr uint16_t COLOR565_PALE_GREEN          = rgb565(152, 248, 152);
constexpr uint16_t COLOR565_PALE_GREEN3         = rgb565(104, 208, 104);
constexpr uint16_t COLOR565_PALE_TURQUOISE      = rgb565(152, 248, 248);
constexpr uint16_t COLOR565_PALE_VIOLET_RED     = rgb565(208, 104, 152);
constexpr uint16_t COLOR565_PERU                = rgb565(208, 152,  48);
constexpr uint16_t COLOR565_PINK                = rgb565(248, 208, 208);
constexpr uint16_t COLOR565_PINK4               = rgb565(152, 104, 104);
constexpr uint16_t COLOR565_PLUM                = rgb565(208, 152, 208);
constexpr uint16_t COLOR565_PLUM1               = rgb565(248, 208, 248);
constexpr uint16_t COLOR565_PLUM4               = rgb565(152, 104, 152);
constexpr uint16_t COLOR565_PURPLE              = rgb565(152,   0, 152);
constexpr uint16_t COLOR565_PURPLE1             = rgb565(152,  48, 248);
constexpr uint16_t COLOR565_PURPLE3             = rgb565(104,  48, 208);
constexpr uint16_t COLOR565_REBECCAPURPLE       = rgb565(104,  48, 152);
constexpr uint16_t COLOR565_RED                 = rgb565(248,   0,   0);
constexpr uint16_t COLOR565_RED3                = rgb565(208,   0,   0);
constexpr uint16_t COLOR565_ROSY_BROWN          = rgb565(208, 152, 152);
constexpr uint16_t COLOR565_ROYAL_BLUE          = rgb565( 48, 104, 208);
constexpr uint16_t COLOR565_ROYAL_BLUE2         = rgb565( 48, 104, 248);
constexpr uint16_t COLOR565_SADDLE_BROWN        = rgb565(152,  48,   0);
constexpr uint16_t COLOR565_SANDY_BROWN         = rgb565(248, 152, 104);
constexpr uint16_t COLOR565_SCARLET_FLAME       = rgb565(152,  48, 104);
constexpr uint16_t COLOR565_SEA_GREEN           = rgb565( 48, 152, 104);
constexpr uint16_t COLOR565_SEA_GREEN1          = rgb565(104, 248, 152);
constexpr uint16_t COLOR565_SEA_GREEN3          = rgb565( 48, 208, 152);
constexpr uint16_t COLOR565_SIENNA              = rgb565(152, 104,  48);
constexpr uint16_t COLOR565_SKY_BLUE3           = rgb565(104, 152, 208);
constexpr uint16_t COLOR565_SLATE_BLUE          = rgb565(104, 104, 208);
constexpr uint16_t COLOR565_SLATE_GRAY4         = rgb565(104, 104, 152);
constexpr uint16_t COLOR565_SPRING_GREEN        = rgb565(  0, 248, 104);
constexpr uint16_t COLOR565_SPRING_GREEN3       = rgb565(  0, 208, 104);
constexpr uint16_t COLOR565_SPRING_GREEN4       = rgb565(  0, 152,  48);
constexpr uint16_t COLOR565_STEEL_BLUE          = rgb565( 48, 152, 208);
constexpr uint16_t COLOR565_STEEL_BLUE1         = rgb565(104, 208, 248);
constexpr uint16_t COLOR565_STEEL_BLUE4         = rgb565( 48, 104, 152);
constexpr uint16_t COLOR565_TAN2                = rgb565(248, 152,  48);
constexpr uint16_t COLOR565_TEAL                = rgb565(  0, 152, 152);
constexpr uint16_t COLOR565_TOMATO              = rgb565(248, 104,  48);
constexpr uint16_t COLOR565_TURQUOISE           = rgb565( 48, 208, 208);
constexpr uint16_t COLOR565_VIOLET              = rgb565(248, 152, 248);
constexpr uint16_t COLOR565_VIOLET_RED          = rgb565(208,  48, 152);
constexpr uint16_t COLOR565_VIOLET_RED1         = rgb565(248,  48, 152);
constexpr uint16_t COLOR565_VIOLET_RED3         = rgb565(208,  48, 104);
constexpr uint16_t COLOR565_WHITE               = rgb565(248, 248, 248);
constexpr uint16_t COLOR565_YELLOW              = rgb565(248, 248,   0);
constexpr uint16_t COLOR565_YELLOW3             = rgb565(208, 208,   0);
constexpr uint16_t COLOR565_YELLOW_GREEN        = rgb565(152, 208,  48);
#endif // COLOR565_H
